<a href="https://colab.research.google.com/github/yesin25/MMD/blob/main/Programa_de_encriptaci%C3%B3n_y_desencriptaci%C3%B3n_de_texto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img width="800px" src="https://static.wikia.nocookie.net/logopedia/images/5/50/Universidad_Ricardo_Palma.jpg/revision/latest?cb=20210407204705&path-prefix=es"></img>
# <font color='Darkgreen'>**Unidad de Posgrado - Maestria en Ciencias de los Datos**</font></span>
## <font color='Green'> **Métodos de Matrices Distribuidas** </font></span>
Alumno: **Camarena - Pachas - Yesin**

Desarrolle en Google Colaboratory un programa que encripte y desencripte los texto que pueden enviar.

### Paso 1: Representar el mensaje como una matriz numérica

In [81]:
import numpy as np


mensaje = "HOY ES EL PRIMER DIA"
mensaje = mensaje.upper()  # Convertir el mensaje a mayúsculas
alfabeto = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
mensaje_numerico = []

for letra in mensaje:
    if letra == " ":  # Manejar espacios en blanco
        mensaje_numerico.append(27)  # Asignar el valor 27 al espacio en blanco
    elif letra in alfabeto:
        mensaje_numerico.append(alfabeto.index(letra) + 1)
    else:
        print(f"Caracter no válido: {letra}")

# Asegurarse de que M tenga 3 columnas
num_filas = len(mensaje_numerico) // 3 + (len(mensaje_numerico) % 3 > 0)
M = np.array(mensaje_numerico + [0] * (num_filas * 3 - len(mensaje_numerico)))
M = M.reshape(3, -1)

# Mostrar la matriz M
print("Matriz M:")
print(M)


Matriz M:
[[ 8 15 25 27  5 19 27]
 [ 5 12 27 16 18  9 13]
 [ 5 18 27  4  9  1  0]]


### Paso 2: Crear una matriz clave fija (A) de 3x3

In [82]:
A = np.array([[-1, 1, 1],
            [-2, -3, 1],
            [3, 1, -2]])

# Mostrar la matriz clave A
print("\nMatriz Clave A:")
print(A)



Matriz Clave A:
[[-1  1  1]
 [-2 -3  1]
 [ 3  1 -2]]


### Paso 3: Multiplicar A por M para obtener el mensaje cifrado (C)

In [93]:
C = np.dot(A, M) # Se aplica módulo 27
print("\nMatriz Cifrada C = AM:")
print(C)


Matriz Cifrada C = AM:
[[   2   15   29   -7   22   -9  -14]
 [ -26  -48 -104  -98  -55  -64  -93]
 [  19   21   48   89   15   64   94]]


### Paso 4: Descifrar el mensaje cifrado multiplicando $A^{-1}*C$

In [94]:

A_inversa = np.linalg.inv(A).round().astype(int)
M_descifrado = np.dot(A_inversa, C).round().astype(int) #% 27

#Mostrar la Matriz inversa
print("\nMatriz Inversa A^(-1):")
print(A_inversa)

# Mostrar la matriz descifrada M
print("\nMatriz Descifrada M= A^(-1)*C:")
print(M_descifrado)


Matriz Inversa A^(-1):
[[ 5  3  4]
 [-1 -1 -1]
 [ 7  4  5]]

Matriz Descifrada M= A^(-1)*C:
[[ 8 15 25 27  5 19 27]
 [ 5 12 27 16 18  9 13]
 [ 5 18 27  4  9  1  0]]


### Paso 5: Decodificar la matriz numérica en un mensaje de texto legible

In [91]:

import numpy as np

# Alfabeto con espacio en blanco
alfabeto = "ABCDEFGHIJKLMNOPQRSTUVWXYZ "

# Función para convertir una matriz de números en un mensaje de texto
def matriz_a_mensaje(matriz):
    mensaje = ""
    filas, columnas = matriz.shape

    for fila in range(filas):
        for columna in range(columnas):
            numero = matriz[fila, columna]
            if numero == 27:  # Espacio en blanco
                mensaje += " "
            elif numero >= 1 and numero <= 26:
                letra = alfabeto[numero - 1]
                mensaje += letra

    return mensaje

# Convertir la matriz descifrada en un mensaje
mensaje_descifrado = matriz_a_mensaje(M_descifrado)
print("Mensaje Descifrado:")
print(mensaje_descifrado)


Mensaje Descifrado:
HOY ES EL PRIMER DIA


In [ ]:
from sympy import Matrix, symbols

# Definir el alfabeto y el mensaje
alfabeto = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
mensaje = "HOY ES EL PRIMER DIA"

# Crear un diccionario para mapear letras a números
letra_a_numero = {letra: i + 1 for i, letra in enumerate(alfabeto)}
letra_a_numero[" "] = 27  # Espacio en blanco

# Convertir el mensaje en una lista de números
mensaje_numerico = [letra_a_numero[letra] for letra in mensaje]

# Calcular el número de columnas necesarias para la matriz
num_columnas = len(mensaje)  # El número de letras en el mensaje

# Crear la matriz numérica
M = Matrix(mensaje_numerico)

# Redimensionar la matriz para que tenga una fila y las columnas necesarias
M = M.reshape(1, num_columnas)

M
